# Generated by Django 4.2.2 on 2023-10-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_bd_user_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['published'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=None, verbose_name='Опубликовано'),
            preserve_default=False,
        ),
    ]
